# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    commands:
      #installs dependencies into the node_modules/ directory
      - cd frontend
      - cp example.env .env.production
      - npm install
      - npm install jsonwebtoken graphql@15.7.2
      - npm install -D typescript @types/jsonwebtoken
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - rm -rf node_modules
      - rm package-lock.json
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
