const Env = {
  BACK_PORT: 'BACK_PORT',
  NODE_ENV: 'NODE_ENV',

  DB_URL: 'DB_URL',

  HOST_FRONT: 'HOST_FRONT',
  BACKEND_URL: 'BACKEND_URL',

  SECRET_JWT_ACCESS: 'SECRET_JWT_ACCESS',
  SECRET_FORGOT: 'SECRET_FORGOT',
  SESSION_KEY: 'SESSION_KEY',

  SECRET_EMAIL: 'SECRET_EMAIL',
  EMAILU: 'EMAILU',
  EMAILP: 'EMAILP',
};

module.exports = Env;
