export enum MainPaths {
  INDEX = '/',
  LOGIN = '/login',
  SIGNUP = '/signup',
  POPULAR = '/popular',
  NEW_RECIPE = '/new-recipe',
  RECIPE = '/recipe/[recipe]',
  SEARCH = '/search',
  PROFILE = '/profile',
  FORGOT_USER_PASSWORD = '/forgot-password',
  FORGOT_USER_PASSWORD_CONFIRM = '/forgot-password/[token]',
  CONFIRMATION = '/confirmation/[token]',
  NOT_FOUND = '/404',
  ADMIN = '/admin/users',
}
