export const MainPaths = {
    INDEX: '/',
    LOGIN: '/login',
    SIGNUP: '/signup',
    POPULAR: '/popular',
    NEW_RECIPE: '/new-recipe',
    RECIPE: '/recipe/[recipe]',
    SEARCH: '/search',
    PROFILE: '/profile',
    FORGOT_PASS: '/forgot-pass',
    FORGOT_PASS_CONFIRM: 'forgot-pass/[token]',
    CONFIRMATION: '/confirmation/[token]',
    NOT_FOUND: '/404',
    ADMIN: '/admin/users',
};